src/auth.ts

it does not seem necessary that we will need to listen on 0.0.0.0. First of all, users will get this popup on macOS
secondly, it does not look safe if user approved it as we get some server exposed on local network?
I haven't tested it locally and just searched for how to pass localhost to `.listen`, so this might not compile. Waiting on CI... Thanks for reviews!

auth: only listen on localhost

---

mocks/bin/psql
mocks/bin/psql.cjs
mocks/main/projects/test/branches/POST.js
package-lock.json
package.json
snapshots/commands/branches.test.snap
snapshots/commands/connection_string.test.snap
snapshots/commands/projects.test.snap
src/commands/branches.test.ts
src/commands/branches.ts
src/commands/connection_string.test.ts
src/commands/connection_string.ts
src/commands/projects.test.ts
src/commands/projects.ts
src/index.ts
src/test_utils/test_cli_command.ts
src/utils/psql.ts

This PR adds `--psql` flag to the following commands:
- `projects create` 
- `branches create` 
- `connection-string`
The flag makes neonctl launch psql session for a given project/branch/connection string.
For non-idempotent operations (`projects create` and `branches create`), it happens after the standard output (with new project/branch information).
For idempotent `connection-string`, it launches psql instead of the output. 
Additional psql arguments can be passed after `--`:
```bash
neonctl branches create --project-id orange-field-03303460 --psql -- -c "SHOW neon.timeline_id"  
branch
┌────────────────────────┬────────────────────────┬─────────┬──────────────────────┬──────────────────────┐
│ Id                     │ Name                   │ Primary │ Created At           │ Updated …
```

feat: --psql flag for providing psql connection to db

---

.gitignore
package-lock.json
src/utils/psql.ts

This PR improves signal handling for `--psql`, particularly Ctrl+C behaviour.
Before: 
```
bayandin@mpb % neonctl cs --project-id <project-id> --psql -- -c "SELECT pg_sleep(60)"
INFO: Connecting to the database using psql...
^C
bayandin@mpb % Cancel request sent
ERROR:  canceling statement due to user request
```
After:
```
bayandin@mpb % neonctl cs --project-id <project-id> --psql -- -c "SELECT pg_sleep(60)"
INFO: Connecting to the database using psql...
^CCancel request sent
Cancel request sent
ERROR:  canceling statement due to user request
bayandin@mpb neonctl % 
```

fix: signal handling with --psql

---

.gitignore
src/utils/psql.ts

This PR improves signal handling for `--psql`, particularly Ctrl+C behaviour.
Before: 
```
bayandin@mpb % neonctl cs --project-id <project-id> --psql -- -c "SELECT pg_sleep(60)"
INFO: Connecting to the database using psql...
^C
bayandin@mpb % Cancel request sent
ERROR:  canceling statement due to user request
```
After:
```
bayandin@mpb % neonctl cs --project-id <project-id> --psql -- -c "SELECT pg_sleep(60)"
INFO: Connecting to the database using psql...
^CCancel request sent
Cancel request sent
ERROR:  canceling statement due to user request
bayandin@mpb neonctl % 
```

fix: signal handling with --psql (#101)

---

src/callback.html

Successful `neonctl auth` redirects you to a really bright callback page.
This PR adds a dark theme to make the page friendly for owls.
Old Light mode:
New Light mode:
New Dark mode:

feat: add dark mode for callback page

---

package.json

Apparently we lost the `prepare` npm script that makes husky work for anyone who installs the project locally, so I managed to overcome it 😅

fix: fix husky

---

.gitignore
generateOptionsFromSpec.ts
mocks/main/projects/test/GET.json
mocks/main/projects/test/PATCH.js
mocks/main/projects/test/PATCH.json
package-lock.json
package.json
snapshots/commands/projects.test.snap
src/commands/projects.test.ts
src/commands/projects.ts
src/parameters.gen.ts

Fixes: https://github.com/neondatabase/cloud/issues/8242
---
https://github.com/neondatabase/neonctl/assets/1949852/d1ef12c9-70d1-4dbd-8341-1fd4a1627337
Commands in video - 
1. Project GET command (local environment)
2. Project UPDATE command with IP Allow configuration (local environment)

feat: ip allow configuration with project update command

---

src/api.ts

We ask our customers to integrate branch creation into their (customers') github workflows.
We don't want our customers to suffer from flaky github workflows due to Neon timeouts.
So a good developer experience needs to make sure that our documentation, sample and blogs provide instructions that will work (even in case our internal network is unstable for a few seconds).
I suggest to increase the timeout to a value that is more resilient to occasional hiccups.
60 seconds was suggested by subject matter expert based on Neon internal testing.

fix: increase timeout when calling Neon public API

---

src/api.ts

We ask our customers to integrate branch creation into their (customers') github workflows.
We don't want our customers to suffer from flaky github workflows due to Neon timeouts.
So a good developer experience needs to make sure that our documentation, sample and blogs provide instructions that will work (even in case our internal network is unstable for a few seconds).
I suggest to increase the timeout to a value that is more resilient to occasional hiccups.
60 seconds was suggested by subject matter expert based on Neon internal testing.

fix: increase timeout when calling Neon public API (#177)

---

snapshots/commands/connection_string.test.snap
src/commands/connection_string.ts

relates: https://github.com/neondatabase/cloud/issues/11987
A while back, we changed connection string examples in the Connection Details widget to use `postgresql://` due to the shorter version (`postgres://`) not working with some framework/driver. Update the connection_string (cs) command to use `postgresql://` scheme while generating the connection string.

fix: connection uri scheme to postgresql

---

src/commands/branches.ts
src/commands/schema_diff.ts
src/index.ts
src/utils/point_in_time.ts

closes: https://github.com/neondatabase/cloud/issues/14004
closes: https://github.com/neondatabase/cloud/issues/14005
closes: https://github.com/neondatabase/cloud/issues/14006
```
$ neonctl branches schema-diff [base-branch] [compare-branch[@timestamp|lsn]] 
```
https://github.com/neondatabase/neonctl/assets/1949852/5962adb7-a736-4308-a8b1-ba767c95f7a4
https://github.com/neondatabase/neonctl/assets/1949852/e7593649-23a3-41cf-ab9f-2b0d29af6340

feat: Add support for Timestamp and LSN for schema diff

---

src/commands/schema_diff.ts

relates: https://github.com/neondatabase/cloud/issues/11846
```sh
➜ node dist branches sd 
ERROR: No branch specified. Your context branch (br-twilight-paper-w2yl38qc) has no parent, so no comparison is possible
➜ node dist branches sd --projectId white-wildflower-12758365
ERROR: No branch specified. Include a base branch or add a set-context branch to continue. Your primary branch has no parent, so no comparison is possible.
```

fix: issue with command without any arguments throwing error (when no context)

---

README.md
mocks/main/projects/test/branches/GET.json
mocks/main/projects/test/branches/br-cloudy-branch-12345678/GET.json
mocks/main/projects/test/branches/br-numbered-branch-123456/GET.json
mocks/main/projects/test/branches/br-sunny-branch-123456/GET.json
mocks/main/projects/test/branches/br-sunny-branch-123456/set_as_default/POST.json
mocks/main/projects/test/branches/br-sunny-branch-123456/set_as_primary/POST.json
mocks/single_project/projects/test-project-123456/branches/GET.json
package-lock.json
package.json
snapshots/commands/branches.test.snap
snapshots/commands/set_context.test.snap
src/commands/branches.test.ts
src/commands/branches.ts
src/commands/connection_string.ts
src/commands/schema_diff.ts
src/parameters.gen.ts
src/utils/enrichers.ts

Closes https://github.com/neondatabase/neonctl/issues/230 and https://github.com/neondatabase/cloud/issues/9951
* Use default branch field instead of primary
* Use set_as_default API endpoint
* Deprecate set-primary CLI command

feat: use default branch field

---

mocks/main/projects/project-id-123/GET.json
snapshots/commands/set_context.test.snap
src/commands/set_context.test.ts
src/commands/set_context.ts
src/context.ts

fix: remove storing and enriching branch to/from context

---

src/commands/projects.ts

as part of https://github.com/neondatabase/neonctl/pull/231 missed to remove the setting `branchId` in context from project create with `--set-context` option.

fix: do not store branchid in context

---

src/commands/projects.ts

as part of https://github.com/neondatabase/neonctl/pull/231 missed to remove the setting `branchId` in context from project create with `--set-context` option.

fix: do not store branchid in context (#237)

---

mocks/single_project/projects/GET.json
mocks/single_project/projects/test-project-123456/GET.json
src/commands/__snapshots__/ip_allow.test.ts.snap
src/commands/ip_allow.test.ts
src/commands/ip_allow.ts

Closes https://github.com/neondatabase/cloud/issues/9951

feat: add protected-only option to IP allow, deprecate primary-only

---

package.json

Added `npm run typecheck` script for ease of usage as I needed to run it a lot to make sure my refactor didn't break anything.

refactor: add typecheck script

---

.gitignore

I use [local history](https://marketplace.visualstudio.com/items?itemName=xyz.local-history) VSCode extension to backup accidentally removed code. It is done by storing all the version of files locally in `.history` directory.
Unfortunately, prettier does try to format files in this directory sometimes stumbling upon merge markers.
Fortunately, prettier does include `.gitignore` to its own ignore list
Unfortunately, it does not include `~/.gitignore` where I keep ignoring my `.history` dir for every git repo
I decided to add `.history` to local `.gitignore` so it is ignored both by git and prettier.

refactor: ignore .history

---

src/auth.ts

Related to https://github.com/neondatabase/cloud/issues/13076
Back-end changes in https://github.com/neondatabase/cloud/pull/15724
**Test**
After deploying back-end change to staging, I tested this change locally `npm start auth -- --oauth-host=https://oauth2-stage.neon.build`
Tested on prod too, worked correctly. `npm start auth -- --oauth-host=https://oauth2.neon.tech`

feat: add org oauth scopes #cloud/13076

---

mocks/main/projects/GET.js
src/commands/__snapshots__/set_context.test.ts.snap
src/commands/set_context.test.ts
src/commands/set_context.ts
src/context.ts

Related to https://github.com/neondatabase/cloud/issues/13076
Changes
* You can now set org context `neonctl set-context --org-id org-round-art-46961103`
* This will set the context for `neonctl projects list` and `neonctl projects create`
**Testing**
You can also reset the context by calling `neonctl set-context` without any params

feat: ability to set org context

---

.devcontainer/devcontainer.json
mocks/main/projects/GET.js
mocks/main/projects/POST.js
src/commands/__snapshots__/projects.test.ts.snap
src/commands/__snapshots__/set_context.test.ts.snap
src/commands/projects.test.ts
src/commands/projects.ts
src/commands/set_context.test.ts
src/commands/set_context.ts
src/context.ts

Changes (org-related features)
* https://github.com/neondatabase/neonctl/pull/226
* https://github.com/neondatabase/neonctl/pull/268

Release Aug 13

---

src/commands/projects.ts

The initial goal was to add `azure` region. However, while adding it, I noticed that `aws-ap-southeast-2` is also missing.

feat: Add `azure-eastus2` and `aws-ap-southeast-2` regions

---

mocks/main/projects/project-id-123/GET.json
mocks/main/projects/test/GET.json
mocks/main/projects/test/PATCH.js
mocks/main/projects/test_project_with_autoscaling/PATCH.js
mocks/main/projects/test_project_with_fixed_cu/PATCH.js
mocks/single_project/projects/test-project-123456/GET.json
src/commands/__snapshots__/branches.test.ts.snap
src/commands/__snapshots__/ip_allow.test.ts.snap
src/commands/__snapshots__/projects.test.ts.snap
src/commands/__snapshots__/set_context.test.ts.snap
src/commands/branches.test.ts
src/commands/branches.ts
src/commands/ip_allow.test.ts
src/commands/ip_allow.ts
src/commands/projects.test.ts
src/commands/projects.ts

This PR:
- removes deprecated set-primary branch command
- removes deprecated --allow-list and --ip-primary-only flags from project update
- removes deprecated --primary-only flag from ip-allow command
- stops displaying the primary field and drops primary-only
It is a continuation of https://github.com/neondatabase/neonctl/pull/232 and closes https://github.com/neondatabase/cloud/issues/18110. 
BREAKING CHANGE: The deprecated set-primary branch command has been removed, deprecated --allow-list and --ip-primary-only project update flags have been removed, --primary-only flag from the ip-allow command has been removed

chore: remove deprecated set-primary command

---

.github/workflows/report-workflow-stats.yml

Move action repo from personal account to org, and bump to last version.

ci: gh-workflow-stats-action: bump version and move action repo

---

src/analytics.ts

resolves https://github.com/neondatabase/cloud/issues/17309
IP address is collected by Segment itself with `context: {direct: true}`, confirmed in Segment debugger.

feat: segment track IPs

---

.github/workflows/report-workflow-stats.yml
src/analytics.ts

- ci: gh-workflow-stats-action: bump version and move action repo (https://github.com/neondatabase/neonctl/commit/51fe65f6d0cc02096f3829127faa0386ef02f7b8)
- feat: segment track IPs (https://github.com/neondatabase/neonctl/commit/2b2092e459922f2b5f8dabdf6c0ded2550e5d67d)

Release 2024-11-24

---

src/utils/enrichers.ts

Noticed this while working on another issue.

perf: small performance improvement

---

src/analytics.ts
src/commands/branches.ts
src/commands/projects.ts
src/index.ts
src/utils/enrichers.ts

Relates to https://github.com/neondatabase/cloud/issues/20941
Because the `cli_started` event is sent at the beginning we can't know the resource ids.
So I added a `cli_command_success` event after the command runs when we have the final context.
These will not be sent on error because I couldn't find a way to get the context on error.
`neon branches list` will send `projectId`
`neon branches get someid` will send `projectId` and `branchId`
`neon branches get main` will send `projectId` and correct `branchId`
`branches restore A B` will send `projectId` and `branchId=A`
`neon me` will send both as `undefined`

feat: send projectId and branchId to Segment

---

package-lock.json
src/commands/projects.ts
src/parameters.gen.ts

This commit introduces new options for project updates, including
`block_vpc_connections` and `block_public_connections`. It also refactors
the existing code for improved readability and maintainability by alphabetically sorting the parameters for the `project update` command.
Use `--block-vpc-connections=false` to set the value to false.
Use `--block-public-connections=false` to set the value to false.
https://github.com/neondatabase/cloud/issues/21903

feat(project-update): add project update options and refactor code (#main)

---

src/commands/projects.ts

Blocked on https://github.com/neondatabase/cloud/pull/23625
This commit introduces new options for project updates, including `block_vpc_connections` and `block_public_connections`.
https://github.com/neondatabase/cloud/issues/21903

feat(project-create): add project create options

---

src/commands/auth.test.ts
src/commands/auth.ts

Handle Auth issues
- Missing credentials file - reauth (added tests)
- Invalid credentials file - reauth
- Incomplete token set  - reauth
- Missing access_token - refresh token
Problem:
We had a lot of auth and refresh token-related issues
- https://github.com/neondatabase/neonctl/issues/282 
- https://github.com/neondatabase/neonctl/issues/253
- https://github.com/neondatabase/neonctl/issues/321
Most of these issues were happening while refreshing tokens.  When a refresh token is missing or API fails to renew the token, it leaves the user in an abrupt state needing to explicitly run `neonctl auth`. 
Solution: 
This change handles different states of the `credentials` file as listed above. Also added unit tests for all these scenarios.

fix: issues with refresh token and auth

---

.github/workflows/release.yml
.releaserc.json

closes #351
a regression was introduced when I tried to sync binary and NPM package versions.
if the binary is generated before release, it's outdated
if it's generated after the release, it's not uploaded
this PR moves the bundle creation to the semantic-release `prepareCmd` hook.
It should run between version bumping and publishing the release.

fix: add binaries creation to semantic-release `prepareCmd` hook

---

.github/workflows/release.yml
.releaserc.json

a regression was introduced on `2.9.1`
if the binary is generated before release, it's outdated if it's generated after the release, it's not uploaded
this release moves the bundle creation to the semantic-release `prepareCmd` hook.
It should run between version bumping and publishing the release.

Release `2.9.2`: Return of the Binaries

---

src/commands/__snapshots__/branches.test.ts.snap
src/commands/branches.test.ts
src/commands/branches.ts

Resolves https://github.com/neondatabase/cloud/issues/24662. 
There is no functionality to show/list endpoints at the moment, so it was scoped to only adding the `name` parameter to `add-compute` sub-command.

feat: add `name` param to add-compute command

---

src/help.ts

Found via `typos --hidden --format brief`

chore: fix typo, descritpion -> description

---

src/commands/branches.ts

Expiring Branches have entered in GA, the command was already available to anyone who had access, but now we show it in the `--help` output.

feat: show `set-expiration` command in the help output
