neondatabase/neonctl

- mocks/main/projects/test/branches/br-cloudy-branch-12345678/DELETE.json
- mocks/main/projects/test/branches/br-cloudy-branch-12345678/GET.json
- mocks/main/projects/test/branches/br-cloudy-branch-12345678/PATCH.js
- mocks/main/projects/test/branches/br-cloudy-branch-12345678/databases/GET.json
- mocks/main/projects/test/branches/br-cloudy-branch-12345678/databases/POST.js
- mocks/main/projects/test/branches/br-cloudy-branch-12345678/databases/test_db/DELETE.json
- mocks/main/projects/test/branches/br-cloudy-branch-12345678/endpoints/GET.json
- mocks/main/projects/test/branches/br-cloudy-branch-12345678/endpoints/POST.json
- mocks/main/projects/test/branches/br-cloudy-branch-12345678/roles/GET.json
- mocks/main/projects/test/branches/br-cloudy-branch-12345678/roles/POST.js
- mocks/main/projects/test/branches/br-cloudy-branch-12345678/roles/test_role/DELETE.json
- mocks/main/projects/test/branches/br-cloudy-branch-12345678/roles/test_role/reveal_password/GET.json
- mocks/main/projects/test/branches/br-cloudy-branch-12345678/set_as_primary/POST.json
- snapshots/commands/branches.test.snap
- snapshots/commands/connection_string.test.snap
- src/commands/branches.test.ts
- src/commands/connection_string.test.ts
> test: passing branch ids with 8 digit suffix should work

- mocks/main/projects/test/branches/GET.json
- mocks/main/projects/test/branches/br-sunny-branch-123456/GET.json
- mocks/main/projects/test/branches/br-sunny-branch-123456/reset/POST.js
- snapshots/commands/branches.test.snap
- snapshots/commands/set_context.test.snap
- src/commands/branches.test.ts
- src/commands/branches.ts
- src/commands/set_context.test.ts
- src/context.ts
- src/test_utils/test_cli_command.ts
also fixed the bug for context overriding passed branch
> feat: reset branch to parent command

- src/commands/branches.ts
> fix: replaced suspend-timeout text to properly display in help

- .gitignore
- package.json
- snapshots/commands/ip_allow.test.snap
- src/commands/index.ts
- src/commands/ip_allow.test.ts
- src/commands/ip_allow.ts
- src/commands/projects.ts
- src/utils/string.ts
- src/writer.ts
closes: https://github.com/neondatabase/cloud/issues/8882
**New Commands:** 
1. `neonctl ip-allow list --projectId <projectId>`
2. `neonctl ip-allow add 192.168.1.1 127.0.0.1-127.0.0.2 --projectId <projectId>`
3. `neonctl ip-allow add 192.168.1.1 --primary-only false --projectId <projectId>`
4. `neonctl ip-allow remove 192.168.1.1 --projectId <projectId>` 
5. `neonctl ip-allow reset --projectId <projectId>`
https://github.com/neondatabase/neonctl/assets/1949852/092e74ea-b61d-4215-b8c0-f4d5a2cebecb
> [cli] - IP Allow list command 

- .gitignore
- package.json
- snapshots/commands/ip_allow.test.snap
- src/commands/index.ts
- src/commands/ip_allow.test.ts
- src/commands/ip_allow.ts
- src/commands/projects.ts
- src/index.ts
- src/utils/string.ts
- src/writer.ts
> feat: release new ip-allow command

- .github/workflows/commitlint.yml
https://github.com/amannn/action-semantic-pull-request
fixes https://github.com/neondatabase/neonctl/issues/160
> ci: add commit lint for PR title"

- mocks/single_project/projects/test-project-123456/GET.json
- snapshots/commands/ip_allow.test.snap
- src/commands/ip_allow.test.ts
- src/commands/ip_allow.ts
> fix: single project case with ip-allow list command

- src/help.ts
- src/index.ts
- src/utils/ui.ts
also needed to display examples and description correctly for restore command
> fix: help formatting

- src/auth.ts
> fix: process OPTIONS request in auth

- snapshots/commands/connection_string.test.snap
- src/commands/connection_string.test.ts
- src/commands/connection_string.ts
- src/utils/point_in_time.ts
https://www.loom.com/share/91962335b5884c0cad4e02a9ed664a58
> feat: point in time connections in the "cs" command

- mocks/main/projects/shared/GET.js
- package.json
- snapshots/commands/projects.test.snap
- src/commands/projects.ts
> fix: include shared projects in project list cmd

- mocks/main/projects/test/branches/br-cloudy-branch-12345678/databases/GET.json
- mocks/main/projects/test/branches/br-sunny-branch-123456/GET.json
- mocks/main/projects/test/branches/br-sunny-branch-123456/databases/GET.json
- snapshots/commands/branches.test.snap
- snapshots/commands/databases.test.snap
- snapshots/commands/set_context.test.snap
- src/commands/connection_string.test.ts
- src/commands/connection_string.ts
Inspired by https://github.com/neondatabase/create-branch-action/issues/50
> fix: validate database name passed to cs command

- mocks/main/projects/test/branches/br-cloudy-branch-12345678/databases/GET.json
- mocks/main/projects/test/branches/br-sunny-branch-123456/GET.json
- mocks/main/projects/test/branches/br-sunny-branch-123456/databases/GET.json
- snapshots/commands/branches.test.snap
- snapshots/commands/connection_string.test.snap
- snapshots/commands/databases.test.snap
- snapshots/commands/set_context.test.snap
- src/commands/connection_string.test.ts
- src/commands/connection_string.ts
- Use `postgresql` scheme for connection string as `postgres` causes issue with some tools
- Validate database name passed to connection-string command
> fix: connection string uri scheme to postgresql

- package-lock.json
- package.json
- src/auth.ts
- src/commands/auth.test.ts
- src/errors.ts
relates: https://github.com/neondatabase/neonctl/issues/216
> fix: add log statements to debug auth issue

- package-lock.json
- package.json
- src/auth.ts
- src/commands/auth.test.ts
- src/errors.ts
relates: https://github.com/neondatabase/neonctl/issues/216
> fix: add log statements to debug auth issue (#220)

- mocks/main/projects/test/branches/br-cloudy-branch-12345678/databases/GET.json
- mocks/main/projects/test/branches/br-sunny-branch-123456/GET.json
- mocks/main/projects/test/branches/br-sunny-branch-123456/databases/GET.json
- snapshots/commands/branches.test.snap
- snapshots/commands/connection_string.test.snap
- snapshots/commands/databases.test.snap
- snapshots/commands/set_context.test.snap
- src/analytics.ts
- src/commands/connection_string.test.ts
- src/commands/connection_string.ts
- src/index.ts
> fix: analytics for error logging

- package-lock.json
- package.json
- src/analytics.ts
- src/commands/branches.ts
- src/commands/schema_diff.ts
- src/index.ts
- src/parameters.gen.ts
- src/utils/point_in_time.ts
- src/writer.ts
> feat: releasing new schema-diff command

- README.md
- mocks/main/projects/project-id-123/GET.json
- mocks/main/projects/test/branches/GET.json
- mocks/main/projects/test/branches/br-cloudy-branch-12345678/GET.json
- mocks/main/projects/test/branches/br-numbered-branch-123456/GET.json
- mocks/main/projects/test/branches/br-sunny-branch-123456/GET.json
- mocks/main/projects/test/branches/br-sunny-branch-123456/set_as_default/POST.json
- mocks/main/projects/test/branches/br-sunny-branch-123456/set_as_primary/POST.json
- mocks/single_project/projects/test-project-123456/branches/GET.json
- package-lock.json
- package.json
- snapshots/commands/branches.test.snap
- snapshots/commands/set_context.test.snap
- src/commands/branches.test.ts
- src/commands/branches.ts
- src/commands/connection_string.ts
- src/commands/index.ts
- src/commands/orgs.ts
- src/commands/schema_diff.ts
- src/commands/set_context.test.ts
- src/commands/set_context.ts
- src/context.ts
- src/parameters.gen.ts
- src/utils/enrichers.ts
> chore: release org list and default branch field

- mocks/main/users/me/organizations/GET.json
- src/commands/__snapshots__/orgs.test.ts.snap
- src/commands/orgs.test.ts
In #225 I was missing adding a test, this adds the missing test
> chore: test the `orgs list` command

- mocks/main/projects/POST.js
- mocks/main/projects/test/branches/GET.json
- mocks/main/projects/test/branches/POST.js
- mocks/main/projects/test/endpoints/POST.js
- mocks/main/projects/test_project_with_autoscaling/PATCH.js
- mocks/main/projects/test_project_with_fixed_cu/PATCH.js
- src/commands/__snapshots__/branches.test.ts.snap
- src/commands/__snapshots__/projects.test.ts.snap
- src/commands/__snapshots__/set_context.test.ts.snap
- src/commands/branches.test.ts
- src/commands/branches.ts
- src/commands/projects.test.ts
- src/commands/projects.ts
- src/utils/compute_units.ts
I was not sure which handles with autoscale to update with the units, so I updated all of them.
> feat: autoscaling units

- src/commands/bootstrap/index.ts
Addressing some feedback from @rishi-raj-jain :
- Showing "Skip this step" instead of "Nowhere"
- Having an exit message
- No longer generating `.dev.vars`
> fix: fixes the generation of .dev.vars, adds exit message

- package-lock.json
- src/commands/bootstrap/index.ts
> fix: color final instructions in green

- src/commands/bootstrap/index.ts
Adds Prisma templates as a supported ORM option in `neonctl create-app`.
> feat: adds Prisma as a supported ORM to neonctl create-app

- src/auth.ts
Changes
* feat: add org oauth scopes #cloud/13076 https://github.com/neondatabase/neonctl/pull/258
> Release Aug 8 2024

- .devcontainer/devcontainer.json
- devcontainer.json
https://containers.dev/implementors/json_reference/#lifecycle-scripts
Auto setup Github codespaces
> build: add dev container steps to auto setup codespaces

- src/index.ts
> fix: return correct neonctl version

- src/commands/__snapshots__/projects.test.ts.snap
- src/commands/projects.ts
Change "Shared with me" to "Shared with you" to align with the console.
> docs: update shared project text

- src/commands/__snapshots__/projects.test.ts.snap
- src/commands/branches.ts
- src/commands/projects.ts
- src/index.ts
- src/log.ts
Changes:
- fix: return correct neonctl version (#271)
- feat: Add azure-eastus2 and aws-ap-southeast-2 regions (#279)
- docs: update shared project text (#278)
- feat: output a warning if the parent branch is protected (#280)
> Release 2024-09-24

- src/commands/bootstrap/index.ts
> fix: create-app should generate dev/ not dev- branch names

- src/analytics.ts
- src/env.test.ts
- src/env.ts
https://github.com/neondatabase/cloud/issues/13352
> feat: add github environment tracking to Segment

- src/analytics.ts
- src/env.test.ts
- src/env.ts
https://github.com/neondatabase/cloud/issues/13352
> feat: add github environment tracking to Segment (#286)

- src/commands/branches.ts
add `current_state` to branch list to show archived state
remove `updated_at` from the branch list, because it is an internal detail
> feat: show archived status on branches

- src/commands/projects.ts
> neonctl release

- src/analytics.ts
- src/commands/auth.ts
This will help us investigate authentication-related issues in the future.
> feat: improve debug logging and error reporting

- .github/workflows/release.yml
AI left the keys out and I didn't check properly... 🤦
> fix: missing keys from last update

- .github/workflows/release.yml
context: https://neondb.slack.com/archives/C037NJJJDAP/p1748861092920419?thread_ts=1748616726.324769&cid=C037NJJJDAP
> fix: Update release.yml - update PAT to Github app

- README.md
- package.json
- src/commands/__snapshots__/connection_string.test.ts.snap
- src/commands/connection_string.ts
Work on https://databricks.atlassian.net/browse/LKB-1466
> feat: add channel_binding to connection string

- src/index.ts
Context: starting auth flow on 401 broke --psql arg that is now fixed
> fix: --psql arg was broken for some of the cases
